### ISSUE TITLE
out of memory after calling update

### ISSUE THREAD

**Issue by edgarriba** [oval-group/logger#3]
each time I call `update()` my device memory grows which in the end raises the following error: 

```
errorRuntimeError: cuda runtime error (2) : out of memory at /home/eriba/software/pytorch/pytorch/torch/lib/THC/generic/THCStorage.cu:66
```

Does anyone experienced something similar?

**Comment by lberrada** [comment]
Hi, could you provide some details about what you're updating with exactly? It seems likely that you are passing a `cuda` tensor wrapped by a Variable. 

If that's the case, the current code does not protect from doing that, and your backward pass may be trying to back-propagate through the updates of the metrics. An easy fix is to make sure you are passing the `data` attribute rather than the variable to the metrics. I will adapt the code to make sure this cannot happen silently.

**Comment by edgarriba** [comment]
@lberrada thanks for your suggestion, it worked. I was passing a cuda autograd variable. However, not sure if I'm doing wrong but visdom takes some time to refresh logged values (~60s). Is it normal? 

I forward to you the code https://github.com/edgarriba/ali-pytorch/blob/master/main.py#L218

**Comment by lberrada** [comment]
Cool. Each metric sends its value to `visdom` when `xp` logs its value (should happen through a call to `xp.log_metric(...)` or `xp.log_with_tag(...)`), not at each of its `update`. This is because the intermediary values given at an `update` are not necessarily significant (e.g. it makes more sense to send the accumulated accuracy over an epoch than the accuracy of each mini-batch). 

If there is still a significant delay between the call to log and the display on `visdom`, it's due to a connection lag or a`visdom` backend issue.

**Comment by edgarriba** [comment]
OK, I see but not totally convinced with your argument.ls. Log accuracies at the end of the epoch it's fine, but I expect to track the loss before the epoch ends. It's quite common to have long epochs and things might go wrong, so tracking losses in "real time" is really helpful. Tensorboard does a good job with this, I'd like to find a similar functionality for pytorch/visdom. Just an opinion. Your library is good overall

**Comment by lberrada** [comment]
Then I suggest you log the metric as frequently as you need it to be visualized, this wouldn't be a problem.

**Comment by lberrada** [comment]
Thanks for the feedback. I'm closing this "out of memory" issue, feel free to open another issue if you have suggestions or problems with visualization.
